services:
  # Backend API Service
  - type: web
    name: get-more-diners-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_SERVICE_API_KEY
        sync: false
      - key: SMS_SERVICE_API_KEY
        sync: false

  # Frontend Service
  - type: web
    name: get-more-diners-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://get-more-diners-backend.onrender.com/api
